name: 'Flutter Version Checker & Auto-Increment'
description: 'Checks Flutter pubspec.yaml version against branch history and auto-increments if needed'
author: 'Abd Alrahman Kanawati'

inputs:
  branch:
    description: 'The branch to check version history against'
    required: true
    default: 'main'
  token:
    description: 'GitHub token for pushing changes (optional - automatically uses GITHUB_TOKEN from environment if not provided)'
    required: false
    default: ''
  commit-message:
    description: 'Custom commit message for version updates'
    required: false
    default: 'Auto-increment version'
  git-user-email:
    description: 'Git user email for commits (defaults to action@github.com for compatibility)'
    required: false
    default: 'action@github.com'
  git-user-name:
    description: 'Git user name for commits'
    required: false
    default: 'GitHub Action Auto-Fix'

outputs:
  previous-version:
    description: 'The previous version found in branch history'
  current-version:
    description: 'The current version after processing'
  version-updated:
    description: 'Whether the version was automatically updated'
  new-version:
    description: 'The new version if updated'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'
  color: 'blue'
