name: 'Flutter Version Checker & Auto-Increment'
description: 'Checks Flutter pubspec.yaml version against branch history and auto-increments if needed (No token required!)'
author: 'Abd Alrahman Kanawati'

inputs:
  branch:
    description: 'The branch to check version history against'
    required: true
    default: 'main'
  commit-message:
    description: 'Custom commit message for version updates'
    required: false
    default: 'Auto-increment version [skip ci]'
  git-user-email:
    description: 'Git user email for commits (defaults to GitHub Actions bot)'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  git-user-name:
    description: 'Git user name for commits'
    required: false
    default: 'github-actions[bot]'

outputs:
  previous-version:
    description: 'The previous version found in branch history'
  current-version:
    description: 'The current version after processing'
  version-updated:
    description: 'Whether the version was automatically updated'
  new-version:
    description: 'The new version if updated'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'
  color: 'blue'
