# Simple Flutter Version Check Example
# Place this file in .github/workflows/ in your Flutter project

name: Simple Flutter Version Check

on:
  push:
    branches: [ main ]

jobs:
  check-version:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout your repository
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important: Need full history to check previous versions
        token: ${{ secrets.GITHUB_TOKEN }}
    
    # Step 2: Run the version checker
    - name: Check and Auto-Increment Version
      id: version
      uses: Abdo-ka/flutter-version-checker@v1
      with:
        branch: main
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "🚀 Auto-increment version [skip ci]"
    
    # Step 3: Use the outputs in your workflow
    - name: Show Results
      run: |
        echo "Previous version: ${{ steps.version.outputs.previous-version }}"
        echo "Current version: ${{ steps.version.outputs.current-version }}"
        echo "Version was updated: ${{ steps.version.outputs.version-updated }}"
        if [ "${{ steps.version.outputs.version-updated }}" == "true" ]; then
          echo "New version: ${{ steps.version.outputs.new-version }}"
        fi
    
    # Step 4: Continue with your Flutter build (example)
    - name: Setup Flutter
      if: success()
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
    
    - name: Build Flutter App
      if: success()
      run: |
        flutter pub get
        flutter build apk --release
        echo "✅ Built Flutter app with version ${{ steps.version.outputs.current-version }}"
